import Jacobians.MappingDegree.AnalyticContinuationGlobalization
import Jacobians.MappingDegree.AnalyticFiberDiscrete
import Jacobians.MappingDegree.AnalyticKthRoot
import Jacobians.MappingDegree.ChartBallOffCentreWitnessDischarge
import Jacobians.MappingDegree.ChartLocalDetour
import Jacobians.MappingDegree.ChartOverlapAvoidanceFull
import Jacobians.MappingDegree.ChartOverlapPropagationDischarge
import Jacobians.MappingDegree.ChartPullbackDataConstruction
import Jacobians.MappingDegree.ChartPullbackNotEventuallyConstDischarge
import Jacobians.MappingDegree.ChartRestrictionToBall
import Jacobians.MappingDegree.ChartedSpaceLocPathConnected
import Jacobians.MappingDegree.ClopennessOfLocallyConstDischarge
import Jacobians.MappingDegree.ConnectedManifoldPathConnected
import Jacobians.MappingDegree.ConnectivityGlobalizationReduction
import Jacobians.MappingDegree.CriticalSetDerivBridge
import Jacobians.MappingDegree.CriticalSetDiscrete
import Jacobians.MappingDegree.CriticalValueSetFinite
import Jacobians.MappingDegree.CriticalValuesFiniteGeneral
import Jacobians.MappingDegree.Degree
import Jacobians.MappingDegree.DegreeWellDefined
import Jacobians.MappingDegree.FibreCardLocallyConstantFromNormalForm
import Jacobians.MappingDegree.FibreCardOnRegularSubset
import Jacobians.MappingDegree.FibreCardWellDefinedAtRegular
import Jacobians.MappingDegree.FibresFiniteAssembly
import Jacobians.MappingDegree.FibresFiniteUnconditional
import Jacobians.MappingDegree.HLcUnconditional
import Jacobians.MappingDegree.HPkgUnconditional
import Jacobians.MappingDegree.HurwitzPatchingDataConstruction
import Jacobians.MappingDegree.HurwitzWellDefinedFromHPath
import Jacobians.MappingDegree.HurwitzWellDefinedUnconditionalTopo
import Jacobians.MappingDegree.IsPathConnectedBallMinusCountable
import Jacobians.MappingDegree.LocalKFoldMultiplicity
import Jacobians.MappingDegree.LocalKFoldMultiplicityFullyUnconditional
import Jacobians.MappingDegree.LocalKFoldMultiplicityUnconditional
import Jacobians.MappingDegree.LocalMultiplicityInvariance
import Jacobians.MappingDegree.LocalNormalForm
import Jacobians.MappingDegree.LocalSheetDataAtRegularValue
import Jacobians.MappingDegree.LocalSheetDataFromContMDiff
import Jacobians.MappingDegree.MeromorphicDivisor
import Jacobians.MappingDegree.PathConnectedComplFinite
import Jacobians.MappingDegree.PathSubdivisionByBallCharts
import Jacobians.MappingDegree.PerChartNonConstancyReduction
import Jacobians.MappingDegree.PreconnectedFromFiniteComplement
import Jacobians.MappingDegree.RegularSubsetPreconnected
import Jacobians.MappingDegree.RegularValueExistsRegUnconditional
import Jacobians.MappingDegree.RegularValueExistsUnconditional
import Jacobians.MappingDegree.RoucheBridge
import Jacobians.MappingDegree.WithinChartWitnessReduction

/-!
# Mapping Degree (`Jacobians/MappingDegree/`)

The mapping degree machine: regular values, critical-value finiteness, fibre counting, well-definedness of the degree (largest unit; contains the ported degree-well-definedness tree).

**Keystones:** `ContMDiff.degree well-definedness engine`

**Builds on units:** local-multiplicity, surfaces-and-charts
-/
