#!/usr/bin/env python3
"""Curate docs/unused_decls.txt into keep/delete categories with LoC estimates.

Categories:
  PROTECTED  referenced by name in the API/audit/conformance/shim surface
  LANDMARK   headline results / unit keystones (kept for the mathematical narrative)
  DELETE     everything else — unreferenced helpers; block LoC estimated from source

Emits docs/unused_decls_curated.md (grouped, with per-unit LoC totals)."""
import collections, os, re

# protected: any identifier appearing in the external surface files
prot = set()
for f in ['AuditAll.lean', 'AxiomCheck.lean', 'ChallengeConformance.lean',
          'ChallengeLeaderboard.lean', 'SubmissionShimTest.lean', 'Jacobians.lean',
          'Jacobian_challenge.lean', 'scripts/axiom_check_final.lean',
          'scripts/comparator_replica.py']:
    prot |= set(re.findall(r'[A-Za-z_][\w]*', open(f).read()))

# landmarks: keystones from unit_design META + headline-ish names
src = open('scripts/unit_design.py').read()
keystones = set(re.findall(r"[A-Za-z_][\w.]*", ' '.join(re.findall(r"\[(?:'[^']*'(?:,\s*)?)+\]", src))))
landmark_rx = re.compile(
    r'(exists_riemannRoch|genus_eq_zero|abelJacobi_twoPoint|hasHolomorphicPrimitives'
    r'|exists_periodLattice_realBasis|residueSum_pairForm_eq_zero_unconditional'
    r'|residueTheorem_formFn_unconditional|lDim_canonical_eq_genus|deg_canonical'
    r'|exists_singleSimplePole|riemannRoch_tailForm|h0Dim_eq_lDim'
    r'|finiteDimensional_cechH1|dbar_solvable|h1Dim_zero_eq_genus)')

DECL_RX = r'^(?:@\[[^\]]*\]\s*)?(?:noncomputable\s+)?(?:protected\s+)?(?:private\s+)?(theorem|def|lemma|structure|abbrev|instance|inductive)\s+((?:_root_\.)?[\w«».]*%s)(?![\w.])'
TOP = re.compile(r'^(@\[|theorem |def |lemma |structure |abbrev |instance |inductive |noncomputable |private |protected |end |section |namespace |/--|/-!)')

def decl_block(path, short):
    """(line, nlines incl. docstring) for declaration `short` in `path`."""
    lines = open(path).read().split('\n')
    rx = re.compile(DECL_RX % re.escape(short))
    for i, l in enumerate(lines):
        if rx.match(l):
            start = i
            # swallow preceding docstring/attribute lines
            j = i - 1
            while j >= 0 and (lines[j].startswith(('@[',)) or lines[j].rstrip().endswith('-/')):
                # walk back to the docstring opener
                if lines[j].rstrip().endswith('-/'):
                    while j >= 0 and not lines[j].lstrip().startswith(('/--', '/-!')):
                        j -= 1
                j -= 1
            start = j + 1
            k = i + 1
            while k < len(lines) and not TOP.match(lines[k]):
                k += 1
            # trim trailing blanks
            while k > i and not lines[k - 1].strip():
                k -= 1
            return i + 1, k - start
    return None, None

rows = []
for line in open('docs/unused_decls.txt'):
    mod, decl = [x.strip() for x in line.split('|')]
    short = decl.split('.')[-1]
    path = mod.replace('.', '/') + '.lean'
    unit = mod.split('.')[1] if mod.count('.') > 1 else 'root'
    if short in prot:
        cat = 'PROTECTED'
    elif short in keystones or landmark_rx.search(decl):
        cat = 'LANDMARK'
    else:
        cat = 'DELETE'
    ln, n = decl_block(path, short) if os.path.exists(path) else (None, None)
    rows.append((cat, unit, mod, decl, ln, n or 0))

out = ['# Unreferenced-declaration curation', '',
       'Generated by scripts/curate_unused.py from docs/unused_decls.txt.',
       'DELETE entries are proposals — review before executing.', '']
tot = collections.Counter()
loc = collections.Counter()
for cat, unit, mod, decl, ln, n in rows:
    tot[cat] += 1
    loc[cat] += n
out.append('| category | decls | est. LoC |')
out.append('|---|---|---|')
for c in ('DELETE', 'LANDMARK', 'PROTECTED'):
    out.append(f'| {c} | {tot[c]} | {loc[c]:,} |')
out.append('')
for cat in ('DELETE', 'LANDMARK', 'PROTECTED'):
    out.append(f'## {cat}')
    out.append('')
    byunit = collections.defaultdict(list)
    for c, unit, mod, decl, ln, n in rows:
        if c == cat:
            byunit[unit].append((mod, decl, ln, n))
    for unit in sorted(byunit, key=lambda u: -sum(x[3] for x in byunit[u])):
        items = byunit[unit]
        out.append(f'### {unit} — {len(items)} decls, ~{sum(x[3] for x in items):,} LoC')
        for mod, decl, ln, n in sorted(items, key=lambda x: -x[3]):
            loc_s = f'{mod.replace(".", "/")}.lean:{ln}' if ln else '(not located)'
            out.append(f'- `{decl}` ({n} LoC) — {loc_s}')
        out.append('')
open('docs/unused_decls_curated.md', 'w').write('\n'.join(out))
print(f"DELETE: {tot['DELETE']} decls ~{loc['DELETE']:,} LoC | "
      f"LANDMARK: {tot['LANDMARK']} | PROTECTED: {tot['PROTECTED']}")
