#!/usr/bin/env python3
"""Generate docs/MODULE_MAP.md: the import-graph layering of all modules with one-line
summaries pulled from each file's module docstring. Run from the repo root."""
import os, re, functools, sys
sys.setrecursionlimit(10000)

imp = re.compile(r'^import (Jacobians[\w.]*)', re.M)
def mod(p): return p[:-5].replace('/', '.')
deps, summary = {}, {}
for root, _, files in os.walk('Jacobians'):
    for f in sorted(files):
        if not f.endswith('.lean'): continue
        p = os.path.join(root, f)
        src = open(p).read()
        deps[mod(p)] = [d for d in imp.findall(src)]
        # prefer the '# Title' heading inside a module docstring; skip copyright headers
        m = re.search(r'^#\s+([^\n]+)', src, re.M)
        if not m:
            m = re.search(r'/-[!-]?\s*\n\s*([A-Z][^\n]+)', src)
        t = (m.group(1).strip(' #-!/') if m else '').rstrip('-/').strip()
        if t.lower().startswith('copyright'): t = ''
        summary[mod(p)] = t

@functools.cache
def layer(m):
    ds = [d for d in deps.get(m, []) if d in deps]
    return 1 + max((layer(d) for d in ds), default=0)

layers = {}
for m in deps: layers.setdefault(layer(m), []).append(m)

with open('docs/MODULE_MAP.md', 'w') as out:
    out.write("# Module map\n\n*Generated by `scripts/module_map.py` — do not edit by hand.*\n\n"
              "Modules grouped by import depth (layer 1 = leaves of the import graph; "
              "higher layers build on lower ones).\n\n")
    for l in sorted(layers):
        out.write(f"## Layer {l}\n\n")
        for m in sorted(layers[l]):
            s = summary.get(m, '')
            out.write(f"- `{m}`" + (f" — {s}" if s else "") + "\n")
        out.write("\n")
print(f"wrote docs/MODULE_MAP.md: {len(deps)} modules, {max(layers)} layers")
